// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'description': string;
  'image_upload': string;
  'plus_icon': string;
}
export const cssExports: CssExports;
export default cssExports;
