// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'comment_field': string;
  'icon': string;
  'upload_btn': string;
}
export const cssExports: CssExports;
export default cssExports;
