// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'close_btn': string;
  'comments_more': string;
  'container': string;
  'content': string;
  'content_container': string;
  'dialog': string;
  'dialog_container': string;
  'image': string;
  'm_text': string;
  'nick_name': string;
  'profile_img': string;
  'root': string;
  's_text': string;
  'scroll_section': string;
  'user': string;
  'user_container': string;
  'user_detail': string;
  'user_name': string;
}
export const cssExports: CssExports;
export default cssExports;
