// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'left_icons': string;
  'like-button-animation': string;
  'like_icon': string;
  'right_icon': string;
}
export const cssExports: CssExports;
export default cssExports;
