// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bottom_icons': string;
  'comment': string;
  'comment-detail': string;
  'comment_container': string;
  'comment_field': string;
  'content_container': string;
  'contents': string;
  'contents_box': string;
  'icon': string;
  'img_container': string;
  'img_section': string;
  'likes': string;
  'm_text': string;
  'nick_name': string;
  's_text': string;
  'show_all_btn': string;
  'timer': string;
  'toggle_box': string;
  'upload_btn': string;
}
export const cssExports: CssExports;
export default cssExports;
