// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'fake_field': string;
  'input': string;
  'search_box': string;
  'search_field': string;
}
export const cssExports: CssExports;
export default cssExports;
