// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'dropdown': string;
  'dropdown_content': string;
  'header': string;
  'inner': string;
  'logo': string;
  'menu_item': string;
  'on': string;
  'right_icons': string;
  'search_field': string;
  'sprite_insta_icon': string;
}
export const cssExports: CssExports;
export default cssExports;
