query getAllPosts($skip: Int, $take: Int) {
  posts(skip: $skip, take: $take) {
    postId
    bookImageURL
    bookName
    content
    comments(skip: 0, take: 2) {
      user {
        userId
        profileImageURL
      }
      content
    }
    user {
      userId
      profileImageURL
    }
    likes {
      likeId
    }
    createdAt
    updatedAt
  }
}
