query getPostAndComments($postId: Int!) {
  post(id: $postId) {
    bookImageURL
    bookName
    content
    user {
      userId
      profileImageURL
    }
    likes {
      likeId
    }
  }
  comments(postId: $postId, skip: 0, take: 5) {
    user {
      userId
      profileImageURL
    }
    content
    createdAt
  }
}
