query getAllPosts {
  posts {
    postId
    bookImageURL
    bookName
    content
    comments {
      user {
        userId
      }
      content
    }
    user {
      userId
    }
    likes {
      likeId
    }
  }
}
