// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'm_text': string;
  'on': string;
  's_text': string;
  'sprite_more_icon': string;
  'toggle_box': string;
  'top': string;
  'user_container': string;
}
export const cssExports: CssExports;
export default cssExports;
