// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content_container': string;
  'dense': string;
  'nick_name': string;
  'profile_img': string;
  'root': string;
  'user': string;
  'user_container': string;
  'user_detail': string;
  'user_id': string;
  'user_name': string;
}
export const cssExports: CssExports;
export default cssExports;
